### ISSUE TITLE
Clear division of 

### ISSUE THREAD

**Issue by nathanshammah** [benmcdonough20/AtonomousPERTools#4]
I suggest to clearly divide in the documentation the two different tools' functionalities:

1.  Tools of the noise characterization 
2.  Tools for error mitigation

**Comment by benmcdonough20** [comment]
Hello Nathan,

Thanks for this suggestion! Could you elaborate a little bit more on what you think should be done?

I don't really see a clean division along these lines. For the two methods we were working on developing, the first uses PyGSTi directly for noise characterization and does not provide functionality beyond what PyGSTi implements. For the second one, the sparse Pauli tomography is pretty heavily integrated with the Pauli noise scaling method of PER, so I'm not sure if it makes sense to separate them.

Let me know what you think, and I am happy to make the changes.
